In [1]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [14]:
import torch

In [15]:
a=torch.tensor([5.],requires_grad=True)
b=torch.tensor([6.],requires_grad=True)

In [16]:
a

tensor([5.], requires_grad=True)

In [17]:
b

tensor([6.], requires_grad=True)

In [18]:
q = a**3 - b**2
q

tensor([89.], grad_fn=<SubBackward0>)

In [19]:
print(a.grad)

None


In [20]:
print(b.grad)

None


In [21]:
q.backward()

In [22]:
a.grad

tensor([75.])

In [23]:
b.grad

tensor([-12.])

In [27]:
w=torch.randn(10,1,requires_grad=True)
bi=torch.randn(1,requires_grad=True)

In [28]:
w

tensor([[ 0.1568],
        [ 0.2681],
        [ 2.5231],
        [ 0.1196],
        [ 0.2164],
        [-0.3320],
        [-1.2650],
        [ 0.1447],
        [-1.7263],
        [ 0.0823]], requires_grad=True)

In [29]:
bi

tensor([-0.7212], requires_grad=True)

In [30]:
x=torch.rand(1,10)
x

tensor([[0.1978, 0.5774, 0.0782, 0.3936, 0.4563, 0.0676, 0.0673, 0.1933, 0.1170,
         0.7761]])

In [34]:
output=torch.matmul(x,w) + bi
output

tensor([[-0.4100]], grad_fn=<AddBackward0>)

In [35]:
loss=1-output
loss

tensor([[1.4100]], grad_fn=<RsubBackward1>)

In [36]:
loss.backward()

In [37]:
w.grad

tensor([[-0.1978],
        [-0.5774],
        [-0.0782],
        [-0.3936],
        [-0.4563],
        [-0.0676],
        [-0.0673],
        [-0.1933],
        [-0.1170],
        [-0.7761]])

In [38]:
with torch.no_grad():
    w= w- 0.001 * w.grad.data

In [39]:
w

tensor([[ 0.1570],
        [ 0.2686],
        [ 2.5231],
        [ 0.1200],
        [ 0.2169],
        [-0.3319],
        [-1.2649],
        [ 0.1449],
        [-1.7262],
        [ 0.0831]])