In [19]:
import torch
import numpy as np

In [20]:
a=torch.rand(3,3)
b=torch.rand(3,3)
d=torch.add(a,b)
d

tensor([[1.2130, 1.8133, 0.8936],
        [1.2047, 0.9287, 1.0943],
        [1.3981, 1.2992, 1.2734]])

In [21]:
a.mul(b)

tensor([[0.3056, 0.8143, 0.1845],
        [0.3524, 0.2120, 0.2692],
        [0.4699, 0.3709, 0.3241]])

In [22]:
a = torch.rand(10000,10000)
b = torch.rand(10000,10000)
a.matmul(b)

tensor([[2534.5303, 2503.8066, 2508.1692,  ..., 2473.7334, 2526.2769,
         2493.0088],
        [2508.1909, 2475.0562, 2474.3271,  ..., 2468.6685, 2499.4075,
         2482.7920],
        [2520.3215, 2511.7490, 2496.9272,  ..., 2491.9861, 2534.5127,
         2498.8059],
        ...,
        [2522.5212, 2505.5327, 2517.2231,  ..., 2493.6333, 2530.7993,
         2514.4556],
        [2521.1868, 2492.5752, 2503.6968,  ..., 2489.9226, 2541.1785,
         2494.7119],
        [2517.5435, 2511.0923, 2500.9326,  ..., 2482.4268, 2516.2834,
         2496.3523]])

In [23]:
l=[2,3,4,5]
a=np.array(l)
arr=torch.from_numpy(a)
print(arr)

tensor([2, 3, 4, 5], dtype=torch.int32)


In [24]:
f=torch.zeros(2,3,dtype=torch.float64)
print(f)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [25]:
a=torch.tensor([5,6,7],dtype=torch.float)
b=torch.tensor([1,2,3],dtype=torch.float)
print(a+b)

tensor([ 6.,  8., 10.])


In [27]:
torch.add(a,b).sum()

tensor(24.)

In [28]:
a.dot(b)

tensor(38.)

In [29]:
mat = torch.randn(3,3)
print("Matrix:", mat)

Matrix: tensor([[-0.6406,  0.8734, -0.1498],
        [-0.4896, -0.2356,  1.4181],
        [-2.2295, -0.4766,  0.7203]])


In [33]:
det_mat = torch.det(mat)
print("Determinant:", det_mat)

Determinant: tensor(-2.7340)
